"""
Python bindings for massconsistent_amr

This package provides Python bindings for the mass-consistent 3D wind solver
and utilities for coupling with wind farm simulators like FLORIS.

Modules:
    pyWindSolver: Low-level C++ bindings (generated by pybind11)
    wind_solver: High-level Python wrapper class (WindSolver)
    floris_coupling: Standalone utilities for exporting wind to FLORIS format

Example:
    >>> from wind_solver import WindSolver
    >>> wind = WindSolver("inputs.i")
    >>> wind.solve()
    >>> velocity = wind.get_velocity()
    >>> wind.finalize()

Example with FLORIS export:
    >>> from wind_solver import WindSolver
    >>> from floris_coupling import quick_export
    >>> wind = WindSolver("inputs.i")
    >>> wind.solve()
    >>> turbines = [(100, 200), (300, 400)]
    >>> wind_data = quick_export(wind, turbines, hub_height=90.0, 
    ...                          output_file="floris_wind.csv")
    >>> wind.finalize()
"""

__version__ = "0.1.0"

# Import the high-level API by default
from .wind_solver import WindSolver
from .floris_coupling import FLORISWindMap, quick_export
from .pywake_coupling import MassConsistentSite, export_to_wasp_grd, to_wasp_grid_site

__all__ = ["WindSolver", "FLORISWindMap", "quick_export", "MassConsistentSite", "export_to_wasp_grd", "to_wasp_grid_site"]
