"""
Python bindings for massconsistent_amr

This package provides Python bindings for the mass-consistent 3D wind solver
and utilities for coupling with wind farm simulators, fire models, and
geochemical solvers.

Main Modules:
    pyWindSolver: Low-level C++ bindings (generated by pybind11)
    wind_solver: High-level Python wrapper class (WindSolver)
    floris_coupling: Wind farm simulator integration (FLORIS)
    pywake_coupling: Wind farm modeling (PyWake)

Subpackages:
    phreeqc_coupling: Geochemical reactive transport (PHREEQC integration)
        - geochemical_coupling: Atmospheric field extraction
        - reactive_transport_coupling: Orchestration workflow
        - phreeqc_utils: PHREEQC input generation
        - netcdf_io: NetCDF and ASCII I/O

Example - Wind Solver:
    >>> from wind_solver import WindSolver
    >>> wind = WindSolver("inputs.i")
    >>> wind.solve()
    >>> velocity = wind.get_velocity()
    >>> wind.finalize()

Example - PHREEQC Reactive Transport Coupling:
    >>> from wind_solver import WindSolver
    >>> from phreeqc_coupling import ReactiveTransportCoupling
    >>> wind = WindSolver("inputs.i")
    >>> wind.solve()
    >>> coupling = ReactiveTransportCoupling(wind)
    >>> amd_result = coupling.run_amd_simulation(output_dir="amd_results/")
    >>> wind.finalize()

Example - FLORIS Export:
    >>> from wind_solver import WindSolver
    >>> from floris_coupling import quick_export
    >>> wind = WindSolver("inputs.i")
    >>> wind.solve()
    >>> turbines = [(100, 200), (300, 400)]
    >>> wind_data = quick_export(wind, turbines, hub_height=90.0, 
    ...                          output_file="floris_wind.csv")
    >>> wind.finalize()
"""

__version__ = "0.1.1"

# Import the high-level API by default
from .wind_solver import WindSolver
from .floris_coupling import FLORISWindMap, quick_export
from .pywake_coupling import MassConsistentSite, export_to_wasp_grd, to_wasp_grid_site

# Conditional imports for optional PHREEQC coupling module
try:
    from .phreeqc_coupling import (
        ReactiveTransportCoupling,
        FieldExtractor,
        AtmosphericField,
        PHREEQCGenerator,
        NetCDFHandler,
        ASCIIExporter,
    )
    _phreeqc_available = True
except ImportError:
    _phreeqc_available = False

# Conditional imports for optional wildfire_levelset coupling module
try:
    from .levelset_coupling import CoupledWindFireSimulation
    _levelset_available = True
except ImportError:
    _levelset_available = False

# Build __all__ based on available modules
__all__ = [
    "WindSolver",
    "FLORISWindMap",
    "quick_export",
    "MassConsistentSite",
    "export_to_wasp_grd",
    "to_wasp_grid_site",
]

if _phreeqc_available:
    __all__.extend([
        "ReactiveTransportCoupling",
        "FieldExtractor",
        "AtmosphericField",
        "PHREEQCGenerator",
        "NetCDFHandler",
        "ASCIIExporter",
    ])

if _levelset_available:
    __all__.append("CoupledWindFireSimulation")
