"""
Python bindings for massconsistent_amr

This package provides Python bindings for the mass-consistent 3D wind solver
and utilities for coupling with wind farm simulators, fire models, and
geochemical solvers.

Modules:
    pyWindSolver: Low-level C++ bindings (generated by pybind11)
    wind_solver: High-level Python wrapper class (WindSolver)
    floris_coupling: Wind farm simulator integration (FLORIS)
    pywake_coupling: Wind farm modeling (PyWake)
    reactive_transport_coupling: Geochemical solver integration (PHREEQC)
    geochemical_coupling: Field extraction for PHREEQC
    phreeqc_utils: PHREEQC input file generation
    netcdf_io: NetCDF and ASCII I/O for atmospheric fields

Example - Wind Solver:
    >>> from wind_solver import WindSolver
    >>> wind = WindSolver("inputs.i")
    >>> wind.solve()
    >>> velocity = wind.get_velocity()
    >>> wind.finalize()

Example - PHREEQC Reactive Transport Coupling:
    >>> from wind_solver import WindSolver
    >>> from reactive_transport_coupling import ReactiveTransportCoupling
    >>> wind = WindSolver("inputs.i")
    >>> wind.solve()
    >>> coupling = ReactiveTransportCoupling(wind)
    >>> amd_result = coupling.run_amd_simulation(output_dir="amd_results/")
    >>> wind.finalize()

Example - FLORIS Export:
    >>> from wind_solver import WindSolver
    >>> from floris_coupling import quick_export
    >>> wind = WindSolver("inputs.i")
    >>> wind.solve()
    >>> turbines = [(100, 200), (300, 400)]
    >>> wind_data = quick_export(wind, turbines, hub_height=90.0, 
    ...                          output_file="floris_wind.csv")
    >>> wind.finalize()
"""

__version__ = "0.1.1"

# Import the high-level API by default
from .wind_solver import WindSolver
from .floris_coupling import FLORISWindMap, quick_export
from .pywake_coupling import MassConsistentSite, export_to_wasp_grd, to_wasp_grid_site

# Conditional imports for optional dependencies
try:
    from .reactive_transport_coupling import ReactiveTransportCoupling
    from .geochemical_coupling import FieldExtractor, AtmosphericField
    from .phreeqc_utils import PHREEQCGenerator
    __all__ = ["WindSolver", "FLORISWindMap", "quick_export", "MassConsistentSite", 
               "export_to_wasp_grd", "to_wasp_grid_site", 
               "ReactiveTransportCoupling", "FieldExtractor", "AtmosphericField", 
               "PHREEQCGenerator"]
except ImportError:
    __all__ = ["WindSolver", "FLORISWindMap", "quick_export", "MassConsistentSite", 
               "export_to_wasp_grd", "to_wasp_grid_site"]
